version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports: 
      - 8082:8000
    volumes:
      - /rails/django_keycloak_demo:/usr/src/app
    command: /bin/bash
    tty: true
    restart: always